sudo: false
language: c

addons:
  apt:
    packages:
    - luarocks
    - pandoc

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -only "011"


